import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/Navbar ";
import Footer from "@/components/Footer ";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
 <body className={inter.className}>
      <Navbar />
        <div className="flex flex-col justify-between items-center p-24 min-h-screen text-white bg-purple-800">
      {children}
        </div>
        <Footer />
        </body>
      </StoreProvider>
    </html>
  );
}
